version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data:ro
      - ./backend:/app/backend
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    ports:
      - "8081:8081"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - REACT_NATIVE_PACKAGER_HOSTNAME=0.0.0.0
    depends_on:
      - backend
    networks:
      - app-network

  # Development service that runs both backend and provides instructions
  development:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data:ro
      - ./backend:/app/backend
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
